### ISSUE TITLE
[ENH] Perhaps, reformat `ref_data.py` (or at least alloy definitions) into a YAML file.

### ISSUE THREAD

**Issue by amkrajewski** [HUISUN24/feasibility_map#8]
Something like:
```yaml
- name: IN625
  source: https://www.supplierswebsite.com/article/32090933
  formula:
  - Ni: 0.6640
  - Cr: 0.2125
  - Fe: 0.0010
  - Nb: 0.0344
  - Mo: 0.0880
```
